#!/bin/bash

# ganglia is set to add/remove nodes dynamically

remote_service_name=`echo $ENSEMBLE_REMOTE_UNIT | cut -d/ -f1`

cluster_already_configured() {
  `grep data_source /etc/ganglia/gmetad.conf | grep -q $remote_service_name`
}
configure_cluster() {
  echo "data_source \"$remote_service_name\" localhost" >> /etc/ganglia/gmetad.conf
  ensemble-log "restart gmetad"
  service gmetad restart || service gmetad start
}
cluster_already_cofigured || configure_cluster

gmond_already_configured() {
  [ -f /etc/ganglia/gmond.conf ] && grep -q $remote_service /etc/ganglia/gmond.conf
}
configure_gmond() {
  mv /etc/ganglia/gmond.conf /etc/ganglia/gmond.conf.dist
  cp templates/gmond.conf /etc/ganglia/gmond.conf
  sed -i "s/GANGLIA_CLUSTER_NAME/$remote_service_name/" /etc/ganglia/gmond.conf
  sed -i "s/GANGLIA_SERVER/localhost/" /etc/ganglia/gmond.conf
  sed -i "s/GANGLIA_LOCATION/monitor/" /etc/ganglia/gmond.conf
  ensemble-log "restart gmond"
  service ganglia-monitor restart || service ganglia-monitor start
}
gmond_already_configured || configure_gmond

relation-set server=`hostname -f`
