#!/bin/bash

set -eu # -x for verbose logging to ensemble debug-log

#apt-get install -qqy debconf-utils 
#
#ensemble-log "Installing default local mailer, postfix"
#echo postfix postfix/main_mailer_type select 'Internet Site' | debconf-set-selections
#echo postfix postfix/mail_name string $HOSTNAME | debconf-set-selections
#DEBIAN_FRONTEND=noninteractive apt-get -y install -qq postfix
#

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq --no-install-recommends gmetad ganglia-webfrontend


#gmetad_aleady_configured() {
#}
#configure_gmetad() {
#}
#gmetad_already_configured || configure_gmetad


apache_already_configured() {
  [ -l /etc/apache2/conf.d/ganglia.conf ]
}
configure_apache() {
  ensemble-log "Configure apache vhost for ganglia"
  if [ -f /etc/ganglia-webfrontend/apache.conf ]; then
    ln -sf /etc/ganglia-webfrontend/apache.conf /etc/apache2/conf.d/ganglia.conf
  fi
}
apache_already_configured || configure_apache

