#!/bin/bash

set -eu # -x for verbose logging to ensemble debug-log

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq --no-install-recommends gmetad ganglia-webfrontend
service gmetad status && service gmetad stop
DEBIAN_FRONTEND=noninteractive apt-get -y install -qq --no-install-recommends ganglia-monitor 
service gmond status && service gmond stop

gmetad_already_configured() {
  false
}
configure_gmetad() {
  mv /etc/ganglia/gmetad.conf /etc/ganglia/gmetad.conf.dist
  cp templates/gmetad.conf /etc/ganglia/gmetad.conf
}
gmetad_already_configured || configure_gmetad

apache_already_configured() {
  [ -L /etc/apache2/conf.d/ganglia.conf ]
}
configure_apache() {
  ensemble-log "Configure apache vhost for ganglia"
  if [ -f /etc/ganglia-webfrontend/apache.conf ]; then
    ln -sf /etc/ganglia-webfrontend/apache.conf /etc/apache2/conf.d/ganglia.conf
  fi
}
apache_already_configured || configure_apache

