#!/bin/bash

set -eu # -x for verbose logging to juju debug-log

juju-log "Adding ppa"
apt-add-repository ppa:mark-mims/hadoop
juju-log "updating cache"
apt-get update

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq --no-install-recommends ganglia-webfrontend=3.1.7-2ubuntu2
DEBIAN_FRONTEND=noninteractive apt-get -y install -qq --no-install-recommends gmetad=3.1.7-2ubuntu2
service gmetad status && service gmetad stop
DEBIAN_FRONTEND=noninteractive apt-get -y install -qq --no-install-recommends ganglia-monitor=3.1.7-2ubuntu2
service gmond status && service gmond stop

gmetad_already_configured() {
  false
}
configure_gmetad() {
  mv /etc/ganglia/gmetad.conf /etc/ganglia/gmetad.conf.dist
  cp templates/gmetad.conf /etc/ganglia/gmetad.conf
}
gmetad_already_configured || configure_gmetad

apache_already_configured() {
  [ -L /etc/apache2/conf.d/ganglia.conf ]
}
configure_apache() {
  juju-log "Configure apache vhost for ganglia"
  if [ -f /etc/ganglia-webfrontend/apache.conf ]; then
    ln -sf /etc/ganglia-webfrontend/apache.conf /etc/apache2/conf.d/ganglia.conf
  fi
}
apache_already_configured || configure_apache

