#!/bin/bash

juju-log "stopping gmond"
service ganglia-monitor stop

juju-log "stopping gmetad"
service gmetad status && service gmetad stop

juju-log "stopping apache"
service apache2 status && service apache2 stop
